<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220080654 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE despedida ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE despedida ADD CONSTRAINT FK_309B3A05BF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE despedida DROP CONSTRAINT FK_309B3A05BF396750');
        $this->addSql('ALTER TABLE despedida ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
