<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223102150 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE client (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE client_reserve (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, asist BOOLEAN NOT NULL, reserve_who BOOLEAN NOT NULL, client_assist_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4DDDAE5F55BAE2E7 ON client_reserve (client_assist_id)');
        $this->addSql('CREATE TABLE despedida (tematica VARCHAR(30) NOT NULL, details TEXT DEFAULT NULL, place VARCHAR(30) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE donkey (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(30) NOT NULL, years INT DEFAULT NULL, race VARCHAR(50) NOT NULL, kilogram DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disponible BOOLEAN NOT NULL, max_weightr DOUBLE PRECISION NOT NULL, photo_url VARCHAR(255) DEFAULT NULL, reserve_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97EDFEF85913AEBF ON donkey (reserve_id)');
        $this->addSql('CREATE TABLE donkey_reserve (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE employee (social_security INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pay (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, method VARCHAR(20) NOT NULL, total DOUBLE PRECISION NOT NULL, state BOOLEAN NOT NULL, facture_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reserve (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reserve_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state BOOLEAN NOT NULL, details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, donkey_reserve_id INT DEFAULT NULL, client_reserve_id INT DEFAULT NULL, pay_id INT NOT NULL, service_id INT NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FE0EA22E9E1BF90 ON reserve (donkey_reserve_id)');
        $this->addSql('CREATE INDEX IDX_1FE0EA22C94793FE ON reserve (client_reserve_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1FE0EA22918501AB ON reserve (pay_id)');
        $this->addSql('CREATE INDEX IDX_1FE0EA22ED5CA9E6 ON reserve (service_id)');
        $this->addSql('CREATE INDEX IDX_1FE0EA228C03F15C ON reserve (employee_id)');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, base_price DOUBLE PRECISION NOT NULL, description TEXT NOT NULL, duration TIME(0) WITHOUT TIME ZONE NOT NULL, max_aphor INT NOT NULL, leenguage VARCHAR(20) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, donkey_id INT DEFAULT NULL, type_service VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD28912B539 ON service (donkey_id)');
        $this->addSql('CREATE TABLE sponsorship (details TEXT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE therapy (place VARCHAR(30) NOT NULL, details TEXT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tour (name VARCHAR(30) NOT NULL, itinerary TEXT NOT NULL, details TEXT DEFAULT NULL, stops INT NOT NULL, audio_explanation BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, nombre VARCHAR(50) NOT NULL, nif VARCHAR(9) NOT NULL, telefono VARCHAR(15) NOT NULL, contrato_firmado BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type_user VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client_reserve ADD CONSTRAINT FK_4DDDAE5F55BAE2E7 FOREIGN KEY (client_assist_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE despedida ADD CONSTRAINT FK_309B3A05BF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE donkey ADD CONSTRAINT FK_97EDFEF85913AEBF FOREIGN KEY (reserve_id) REFERENCES donkey_reserve (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reserve ADD CONSTRAINT FK_1FE0EA22E9E1BF90 FOREIGN KEY (donkey_reserve_id) REFERENCES donkey_reserve (id)');
        $this->addSql('ALTER TABLE reserve ADD CONSTRAINT FK_1FE0EA22C94793FE FOREIGN KEY (client_reserve_id) REFERENCES client_reserve (id)');
        $this->addSql('ALTER TABLE reserve ADD CONSTRAINT FK_1FE0EA22918501AB FOREIGN KEY (pay_id) REFERENCES pay (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reserve ADD CONSTRAINT FK_1FE0EA22ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reserve ADD CONSTRAINT FK_1FE0EA228C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD28912B539 FOREIGN KEY (donkey_id) REFERENCES donkey (id)');
        $this->addSql('ALTER TABLE sponsorship ADD CONSTRAINT FK_C0F10CD4BF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE therapy ADD CONSTRAINT FK_BEFB2722BF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969BF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D76BF396750');
        $this->addSql('ALTER TABLE client DROP CONSTRAINT FK_C7440455BF396750');
        $this->addSql('ALTER TABLE client_reserve DROP CONSTRAINT FK_4DDDAE5F55BAE2E7');
        $this->addSql('ALTER TABLE despedida DROP CONSTRAINT FK_309B3A05BF396750');
        $this->addSql('ALTER TABLE donkey DROP CONSTRAINT FK_97EDFEF85913AEBF');
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A1BF396750');
        $this->addSql('ALTER TABLE reserve DROP CONSTRAINT FK_1FE0EA22E9E1BF90');
        $this->addSql('ALTER TABLE reserve DROP CONSTRAINT FK_1FE0EA22C94793FE');
        $this->addSql('ALTER TABLE reserve DROP CONSTRAINT FK_1FE0EA22918501AB');
        $this->addSql('ALTER TABLE reserve DROP CONSTRAINT FK_1FE0EA22ED5CA9E6');
        $this->addSql('ALTER TABLE reserve DROP CONSTRAINT FK_1FE0EA228C03F15C');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD28912B539');
        $this->addSql('ALTER TABLE sponsorship DROP CONSTRAINT FK_C0F10CD4BF396750');
        $this->addSql('ALTER TABLE therapy DROP CONSTRAINT FK_BEFB2722BF396750');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969BF396750');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE client_reserve');
        $this->addSql('DROP TABLE despedida');
        $this->addSql('DROP TABLE donkey');
        $this->addSql('DROP TABLE donkey_reserve');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE pay');
        $this->addSql('DROP TABLE reserve');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE sponsorship');
        $this->addSql('DROP TABLE therapy');
        $this->addSql('DROP TABLE tour');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
